import{a as L,i as u,S as b}from"./assets/vendor-6e0bf343.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",v="43225005-d66d61a579372833bf726388e";async function p(t,i,n=15){const o=new URLSearchParams({key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:n});try{const e=await L.get(`${S}?${o}`);return console.log("totalHits:",e.data.totalHits),e.data}catch(e){throw console.error("Error fetching images:",e),e}}function f(t){return t.map(({webformatURL:i,largeImageURL:n,tags:o,views:e,downloads:r,likes:s,comments:h})=>`
    <li class="imageItme">
    <a class="gallery-link" href="${n}">
    <img class="imgAdd" src="${i}" alt="${o}">
    <ul class="imgInfo">
    <li class="info_item"><p>Likes</p>${s}</li>
    <li class="info_item"><p>Views</p>${e}</li>
    <li class="info_item"><p>Comments</p>${h}</li>
    <li class="info_item"><p>Downloads</p>${r}</li>
    </ul>
    </a>
    </li>
`).join("")}const w=document.querySelector(".form"),m=document.querySelector(".gallery"),d=document.getElementById("loader"),a=document.querySelector("#nameImg"),l=document.querySelector(".btn_load_more");w.addEventListener("submit",_);let y="",c=1;function _(t){t.preventDefault();let i=1;if(y=a.value,l.style.display="none",m.innerHTML="",a.value===""){u.error({position:"topRight",message:"The field is empty! Enter image name!"});return}const{nameImg:n}=t.currentTarget.elements;p(n.value,i).then(o=>{o.total===0&&u.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),(o.total===0||o.totalHits<=i*15)&&(l.style.display="none"),m.innerHTML=f(o.hits),g()}).catch(o=>alert(o)).finally(()=>{d.style.display="none"}),l.style.display="block",a.value=""}function g(){new b(".gallery a",{overlayOpacity:.8,scrollZoom:!1,captionsData:"alt",captionDelay:250}).refresh()}l.addEventListener("click",I);function I(){c++,p(y,c).then(t=>{if(t.total===0||t.totalHits<=c*15)l.style.display="none",u.warning({position:"topRight",message:"We're sorry, but you've reached the end of search results."});else{const i=document.querySelector(".imageItme").getBoundingClientRect().height;m.innerHTML+=f(t.hits),g(),window.scrollBy({top:2*i,behavior:"smooth"})}}).catch(t=>alert(t)).finally(()=>{d.style.display="none"})}
//# sourceMappingURL=commonHelpers.js.map
