import{a as L,i as c,S as b}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",v="43225005-d66d61a579372833bf726388e";async function p(i,t,n=15){const o=new URLSearchParams({key:v,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n});try{return(await L.get(`${S}?${o}`)).data}catch(e){throw console.error("Error fetching images:",e),e}}function y(i){return i.map(({webformatURL:t,largeImageURL:n,tags:o,views:e,downloads:r,likes:l,comments:h})=>`
    <li class="imageItme">
    <a class="gallery-link" href="${n}">
    <img class="imgAdd" src="${t}" alt="${o}">
    <ul class="imgInfo">
    <li class="info_item"><p>Likes</p>${l}</li>
    <li class="info_item"><p>Views</p>${e}</li>
    <li class="info_item"><p>Comments</p>${h}</li>
    <li class="info_item"><p>Downloads</p>${r}</li>
    </ul>
    </a>
    </li>
`).join("")}const I=document.querySelector(".form"),u=document.querySelector(".gallery"),f=document.getElementById("loader"),a=document.querySelector("#nameImg"),s=document.querySelector(".btn_load_more");I.addEventListener("submit",q);let d="",m=1;function q(i){i.preventDefault();let t=1;if(d=a.value,s.style.display="none",u.innerHTML="",a.value===""){c.error({position:"topRight",message:"The field is empty! Enter image name!"});return}const{nameImg:n}=i.currentTarget.elements;p(n.value,t).then(o=>{o.total===0&&c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),(o.total===0||o.totalHits<=t*15)&&(s.style.display="none"),u.innerHTML=y(o.hits),g()}).catch(o=>alert(o)).finally(()=>{f.style.display="none"}),s.style.display="block",a.value=""}function g(){new b(".gallery a",{overlayOpacity:.8,scrollZoom:!1,captionsData:"alt",captionDelay:250}).refresh()}s.addEventListener("click",w);function w(){m++;let i=document.querySelectorAll(".imageItme");p(d,m).then(t=>{if(t.total===0||t.totalHits===i.length)s.style.display="none",c.warning({position:"topRight",message:"We're sorry, but you've reached the end of search results."});else{const n=document.querySelector(".imageItme").getBoundingClientRect().height;u.innerHTML+=y(t.hits),g(),window.scrollBy({top:2*n,behavior:"smooth"})}i=document.querySelectorAll(".imageItme"),t.totalHits==i.length&&(s.style.display="none")}).catch(t=>alert(t)).finally(()=>{f.style.display="none"})}
//# sourceMappingURL=commonHelpers.js.map
